INSERT INTO public.rms_studio_service_catalog(service_key,service_name,starting_price_cents,pricing_type,customer_receives,rights_received,customer_does_not_receive,revision_scope,delivery_expectation,refund_cancellation_terms,third_party_content_disclosure,active,founder_approved) VALUES
('remote_recording','Remote recording session',NULL,'written_quote','Guided remote vocal, instrument or spoken-word capture','Only the permissions and deliverables in the approved written scope; no automatic transfer of master or publishing rights','No automatic membership, physical rental, ticket admission, exclusive rights or guaranteed result','Agreed per written project scope before payment','Schedule and delivery confirmed per project before payment','Cancellation and refund terms confirmed per project before payment','All supplied music, samples, performances, voices and likenesses require appropriate permissions',false,false),
('remote_own_setup','Bring your own setup',NULL,'written_quote','Coordinated remote session using the customer''s own setup; no physical venue or equipment rental','Only the permissions and deliverables in the approved written scope; no automatic transfer of master or publishing rights','No automatic membership, physical rental, ticket admission, exclusive rights or guaranteed result','Agreed per written project scope before payment','Schedule and delivery confirmed per project before payment','Cancellation and refund terms confirmed per project before payment','All supplied music, samples, performances, voices and likenesses require appropriate permissions',false,false),
('podcast_interview','Podcast & interview',NULL,'written_quote','Guest coordination, recording and agreed episode delivery','Only the permissions and deliverables in the approved written scope; no automatic transfer of master or publishing rights','No automatic membership, physical rental, ticket admission, exclusive rights or guaranteed result','Agreed per written project scope before payment','Schedule and delivery confirmed per project before payment','Cancellation and refund terms confirmed per project before payment','All supplied music, samples, performances, voices and likenesses require appropriate permissions',false,false),
('performance_capture','Performance & content capture',NULL,'written_quote','Agreed music, poetry, storytelling or creator capture','Only the permissions and deliverables in the approved written scope; no automatic transfer of master or publishing rights','No automatic membership, physical rental, ticket admission, exclusive rights or guaranteed result','Agreed per written project scope before payment','Schedule and delivery confirmed per project before payment','Cancellation and refund terms confirmed per project before payment','All supplied music, samples, performances, voices and likenesses require appropriate permissions',false,false),
('open_mic_production','Open mic production',NULL,'written_quote','Organizer production and running order; admission tickets sold separately','Only the permissions and deliverables in the approved written scope; no automatic transfer of master or publishing rights','No automatic membership, physical rental, ticket admission, exclusive rights or guaranteed result','Agreed per written project scope before payment','Schedule and delivery confirmed per project before payment','Cancellation and refund terms confirmed per project before payment','All supplied music, samples, performances, voices and likenesses require appropriate permissions',false,false),
('poetry_slam_production','Poetry slam & spoken word',NULL,'written_quote','Organizer production; no contest entry or prize entitlement','Only the permissions and deliverables in the approved written scope; no automatic transfer of master or publishing rights','No automatic membership, physical rental, ticket admission, exclusive rights or guaranteed result','Agreed per written project scope before payment','Schedule and delivery confirmed per project before payment','Cancellation and refund terms confirmed per project before payment','All supplied music, samples, performances, voices and likenesses require appropriate permissions',false,false),
('workshop_listening','Workshops & listening parties',NULL,'written_quote','Agreed facilitation, lesson or listening-session production','Only the permissions and deliverables in the approved written scope; no automatic transfer of master or publishing rights','No automatic membership, physical rental, ticket admission, exclusive rights or guaranteed result','Agreed per written project scope before payment','Schedule and delivery confirmed per project before payment','Cancellation and refund terms confirmed per project before payment','All supplied music, samples, performances, voices and likenesses require appropriate permissions',false,false),
('launch_showcase_event','Launches, showcases & branded events',NULL,'written_quote','Agreed release launch, showcase or sponsored creator production','Only the permissions and deliverables in the approved written scope; no automatic transfer of master or publishing rights','No automatic membership, physical rental, ticket admission, exclusive rights or guaranteed result','Agreed per written project scope before payment','Schedule and delivery confirmed per project before payment','Cancellation and refund terms confirmed per project before payment','All supplied music, samples, performances, voices and likenesses require appropriate permissions',false,false) ON CONFLICT(service_key) DO NOTHING;

CREATE TABLE public.rms_reset_service_routes (
 public_service_slug text PRIMARY KEY,
 service_key text NOT NULL REFERENCES public.rms_studio_service_catalog(service_key),
 payment_lane text NOT NULL CHECK (payment_lane IN ('reset_media_studios','reset_live_events')),
 route_enabled boolean NOT NULL DEFAULT false CHECK (NOT route_enabled),
 quote_required boolean NOT NULL DEFAULT true CHECK (quote_required),
 auto_fulfillment_enabled boolean NOT NULL DEFAULT false CHECK (NOT auto_fulfillment_enabled),
 updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.rms_reset_service_routes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.rms_reset_service_routes FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE ON public.rms_reset_service_routes TO service_role;
INSERT INTO public.rms_reset_service_routes(public_service_slug,service_key,payment_lane) VALUES
('beat','custom_production','reset_media_studios'),
('recording','remote_recording','reset_media_studios'),
('own-setup','remote_own_setup','reset_media_studios'),
('podcast','podcast_interview','reset_media_studios'),
('mix','mix_master','reset_media_studios'),
('performance','performance_capture','reset_media_studios'),
('open-mic','open_mic_production','reset_live_events'),
('poetry','poetry_slam_production','reset_live_events'),
('workshop','workshop_listening','reset_live_events'),
('event','launch_showcase_event','reset_live_events');

